# Generated by Django 4.1.2 on 2022-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('site_link', models.CharField(max_length=200)),
                ('rating', models.JSONField()),
                ('plot', models.CharField(max_length=1000)),
                ('language', models.JSONField()),
                ('similar', models.JSONField()),
                ('year_of_release', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.JSONField()),
                ('cast', models.JSONField()),
                ('reviews', models.JSONField()),
                ('platform', models.JSONField()),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
